# this is a config that other rom-rb shares

sources:
  - repo: rom-rb/template-gem
    sync:
      - "config.yml:.action_hero.yml"
      - "!.github/workflows/ci.yml"
      - ".github/**/*.*"
      - "spec/*"
      - "*"
  - repo: action-hero/workflows
    sync:
      - ".github/workflows/*.yml"
